### ISSUE TITLE
Can not login to the project.

### ISSUE THREAD

**Issue by gorogoroyasu** [catalyst-team/mlcomp#12]
I'm trying to use this awesome project, though I failed to login to my project.
I installed via pip (`pip install mlcomp`), and I executed a command `mlcomp init`, then a file was created at `~/mlcomp/configs/.env` as you mentioned in the README.md file.
After that I modified the 2 params shown below.

```
TOKEN=tokentoken
WEB_PORT=20011
```

The port number was successfully changed, though token was not. I put the keyword `tokentoken` to the login form, but the message `Invalid token` is shown.

First of all, I tried with default token, though the situation was same.

The environment I'm using is

- docker image based on nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04
- Python 3.7.4
- mlcomp==19.10

If some additional information is needed, please ask me.

I hope you the great team will tell me how to change token and/or login to the project.
Thank you.

**Comment by gorogoroyasu** [comment]
I found a solution, and prepared a PR.

**Comment by lightforever** [comment]
Amazing work, thank you!

There is a release mlcomp==19.10a with your fix!
