### ISSUE TITLE
How do you specify the gpu ids to use?

### ISSUE THREAD

**Issue by power0341** [catalyst-team/mlcomp#14]
In case, the gpu 0 to 5 have already been used, how could i make use of gpu 6 or 7, I had tried CUDA_VISIBLE_DEVICES=6,7 but seemed NO EFFECT at all, neither did changing the gpu parameter in yml file to range like gpu: 6-7.

**Comment by lightforever** [comment]
I have just added some new functionality. Could you, please, install ```pip install mlcomp==19.10b``` or pull from master.

Then, you can specify the environment variable at the start of the worker:

stop the worker: ```mlcomp-worker stop```
start the worker with the specified environment variable: ```CUDA_VISIBLE_DEVICES=6,7 mlcomp-worker start```

Please note, that ```gpu``` section in .yml files specifies only gpu count, not the indexes.

**Comment by power0341** [comment]
@lightforever i tried to make hot-restart the workers after had mlcomp upgraded to version 19.10b0, but was unable to make it work still. The problem is, once the workers stopped, they can't get started again unless I restart the server.

**Comment by lightforever** [comment]
@power0341, pardon for such a pause.

Could you, please try to install ```pip install mlcomp==19.10rc0``` and retry. I think the bug has been fixed.

**Comment by power0341** [comment]
@lightforever have a look pls
![0](https://user-images.githubusercontent.com/2802813/66695309-b5550700-ecf2-11e9-8d35-d4c480e25a17.png)
![1](https://user-images.githubusercontent.com/2802813/66695310-b5ed9d80-ecf2-11e9-8187-1593edeb94bf.png)
![2](https://user-images.githubusercontent.com/2802813/66695312-b7b76100-ecf2-11e9-8e95-62824b48d049.png)
![3](https://user-images.githubusercontent.com/2802813/66695313-b9812480-ecf2-11e9-8858-64306143dbab.png)

**Comment by lightforever** [comment]
Could you, please:

1. Provide me with the logs: ```tail -n 50 ~/mlcomp/logs/log.txt``` (after not-working restart)

2. Show the logs tab on the web site

3. Try to start in the different way: ```CUDA_VISIBLE_DEVICES=3 mlcomp-worker start --daemon=False --log_level=DEBUG```

4. Try to restart without CUDA_VISIBLE_DEVICES: ```mlcomp-worker start --daemon=False --log_level=DEBUG```. Does the problem repeat?

**Comment by lightforever** [comment]
@power0341, I have managed to reproduce your case. It seems that you are starting mlcomp in such a way: ```mlcomp-server start``` (that command starts server and worker). If you want to start only server, there is a command ```mlcomp-worker start-site``` :)

Then, ```mlcomp-worker stop``` (that command kills worker and server because they are started together) and ```CUDA_VISIBLE_DEVICES=3 mlcomp-worker start``` (starts only worker but not server). Am I correct?

The the solution should be: starting with the following command:

```CUDA_VISIBLE_DEVICES=3 mlcomp-server start``` That is it.

**Comment by power0341** [comment]
yes,   `CUDA_VISIBLE_DEVICES=3 mlcomp-server start` that works now !!!!!
Thanks a lot

**Comment by lightforever** [comment]
You are welcome!
